language: ruby
bundler_args: --without guard
rvm:
  - "2.3.0"
  - "2.3.1"
  - ruby-head
rust:
  - nightly
  - beta
  - stable
before_install: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y && source ~/.cargo/env
script: "bundle exec rake"
branches:
  only: master
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
